### ISSUE TITLE
User: starting package

### ISSUE THREAD

**Issue by sofiapoh** [quaker-social-action/dte-website#1]
As a user, I want to quickly get an idea of the price ranges of funerals that are out there so that I can have a starting point for my decisions.

**Comment by DuncanMcLaggan** [comment]
This would be a "simple funeral service" (cremation or burial) - This will generally be priced into a package, which should include:

o   Collection / transport of body
o   Funeral director professional services 
o   Doctors fee
o   Coffin
o   Hearse
o   Officiate/celebrant fee
o   Crematorium fee or burial fee

Price - depends on the region; cremation or burial. We are collating the average for crem v burial

**Comment by DuncanMcLaggan** [comment]
Regional average costs cremation and burial sent through by email.

**Comment by DuncanMcLaggan** [comment]
Sent through draft text for the option 2 pricing page structure.
