### ISSUE TITLE
Feature update

### ISSUE THREAD

**Issue by RichAWarren** [quaker-social-action/dte-website#10]
Re questions from yesterday:
1. ```
     Fiona is working to bring the package component and pricing data together this week, and this will help us re the number of questions
   ```
2. ```
     We are pitching this as a basic tool, pointing people toward the costs/components of a very basic to slightly more personalised option. This won’t be for those currently faced with a bereavement (for which we would need to refer them to our phone/face to face support if they are on a low income). It serves a public/consumer awareness and “light” planning tool for people regarding a simple funeral. 
   ```
3. ```
     We are unsure about how to present the calculator. We thought it a good idea to present a range of 3-4 package options at the start (eg from direct cremation (the most basic), to hearse + limo (simple), to more personalised (simple +), but then they move through to a general planning tool, rather than one specific to the packages presented. 
   ```
4. ```
     You asked about hints and tips. We think this would be best as a hover function, as there are items which vary hugely in costs and it would be good on these options particularly to have the hover function to highlight this as people move through the options. 
   ```
5. ```
     At the end / what next: At the end we want people to have a basic package/plan which they could then print/save/email. We would not be referring to any FDs. It might be worth linking to the Fair Funerals pledge map though so that people can see if there is a Fair Funerals signatory in their area (http://fairfuneralscampaign.org.uk/map) – we don’t want the general public contacting DtE for general info or questions coming out of this tool, we would only want people immediately faced with a bereavement and likely to struggle with the costs to contact us directly. So we think there should be something which points these clients to us at the beginning, but no specific referral to contact us at the end. 
   ```
6. ```
     Re pricing, we are going to do this on average prices. So we need to make clear to users that this is the case and that they should check directly with their local FDs (get quotes!) to confirm prices. Also some of the prices of individual components vary so much that we may need to price them in ranges – do you think that is possible in terms of calculating costs in the tool? E.g they come out with a plan that has a price range, rather than a specific price. 
   ```
7. ```
     General FAQs section. There are additional pointers that would be useful for users which won’t all be easily covered by the hover hints&tips. We think there could be a general FAQs section added somewhere also.
   ```

**Comment by RichAWarren** [comment]
Agree on all the points above although i feel that may be quite a lot for a 4 day sprint so may need some prioritisation next week as we see how quick progress is. As a start I would suggest we work on the basic user stories outlined in the design sprint, then move on to features such as 4, 5, 7. 

Re 6, it wouldn't be a problem to display the prices in a range providing we have the lower and upper bound for each part of the process that isn't a fixed cost.

**Comment by nogainbar** [comment]
Closing the issue as it belongs to the first sprint.
