### ISSUE TITLE
footer - contact page 

### ISSUE THREAD

**Issue by nogainbar** [quaker-social-action/dte-website#100]
What should go there?

contact information? contact form? links?

@DuncanMcLaggan

**Comment by DuncanMcLaggan** [comment]
Will check with Fiona tomorrow and get back to you.

**Comment by DuncanMcLaggan** [comment]
Hi - for the contact us section can we have:

**Faced with paying for a funeral and need help now? Call us on 0208 983 5055**

**For general information about planning for a funeral and our Down to Earth project visit our website** (add link http://www.quakersocialaction.org.uk/Pages/Category/down-to-earth)

**Want to know more about how we are campaigning for fair funerals? Check out the Fair Funerals campaign** (link to http://fairfuneralscampaign.org.uk/)

**Comment by nogainbar** [comment]
Hi Duncan,

Thats great, thank you!

I will add these things today.
