### ISSUE TITLE
Routing and toggling classes

### ISSUE THREAD

**Issue by sofiapoh** [quaker-social-action/dte-website#101]
Simply adding a class that sets display:none to the page we want to hide when another route is set doesn't actually hide it since fullpage.js automatically sets the page to the full height of the window. We need to either unmount the anchor somehow or figure out another way to do this...

**Comment by gabrielperales** [comment]
I'm doing somthing like this:

``` javascript
  // Routing
  window.addEventListener('hashchange', function(){
    var route = location.hash.replace('#', '');

    switch (route) {
      case 'direct-cremation':
        $('.section.options').hide();
        $('.section.cremation-direct').show();
        break;
      case 'direct':
        $('.section.options').hide();
        $('.section.direct').show();
        break;
      case 'bespoke':
        $('.section.options').hide();
        $('.section.bespoke').show();
        break;
      default:
        break;
    }

  }, false);

```

we just have to add the classname `options` to all the sections that we want to toggle.
So we will be hiding them with `$('.section.options').hide()` and then we will show the slides/screen we want to show adding other class to those sections and we can do `$('.section.otherClass').show()`

**Comment by sofiapoh** [comment]
Okay, if we do this we might have to give up fullpage.js as it doesn't let you really hide pages with just css. I was thinking we could just simply ajax-load the route chosen maybe? Are you working on this right now?
