### ISSUE TITLE
Migrating to harp

### ISSUE THREAD

**Issue by gabrielperales** [quaker-social-action/dte-website#125]
Hi girls!, I saw that you are creating html pages for sections. I have started to migrate the website to harp.

Harp is a static site generator, it allows you to have partials con compilate your partials into different htmls, so you don't have to be copying and pasting html chunks. I think it is pretty easy to use, and also is a cool tool to learn (founders and coders website is build using it!).

I haven't done a pull request, but I have created a new branch ("version/harp") where I'm starting to do the migration. I you are happy with that, you can make a pull request and merge it with master.

**Comment by nogainbar** [comment]
Hey Gabriel!

We think that is a great idea, we would love that if you think that is the best option,

FAC's website was also written in markup, is this part of harp or a separate thing?

thank you!!

**Comment by nogainbar** [comment]
@gabrielperales can we merge a this now to master or you want to wait with it more?
