### ISSUE TITLE
Monday Standup questions

### ISSUE THREAD

**Issue by RichAWarren** [quaker-social-action/dte-website#17]
Fit with existing website design?
How would it integrate with you website, separate?
Data/info, package options?
Design - colours?

**Comment by DuncanMcLaggan** [comment]
Slider? Think we might ditch this - go for basic regional pricing instead using regional averages which we have. 
Colours - to fit with the QSA brand colours - see logo at www.quakersocialaction.org.uk (purple/white/orange)
Data - mostly have, but trying to just get a bit of info to confirm the regional differences between cremation and burial.
