### ISSUE TITLE
Clarification on basic and bespoke packages

### ISSUE THREAD

**Issue by RichAWarren** [quaker-social-action/dte-website#19]
Just to clarify:
The minimum package story would link to a page detailing what that includes, irrespective of location.

Would the basic and bespoke both lead through to the region picker? Or is the basic a fixed cost too?

**Comment by fionasingleton** [comment]
Yes basic and bespoke both benefit from the region picker

**Comment by DuncanMcLaggan** [comment]
the direct cremation (most basic) has no regional differentiation – just a price range of 999-1600, and a reference to the client to confirm with local Funeral Director or google search. 
The basic funeral package and the more bespoke one do have regional differences, which you can see on the data I sent through (so effectively this is where any sort of price calculator kicks in)

**Comment by nogainbar** [comment]
closing issue as was done in last sprint
