### ISSUE TITLE
still bug on iphone SE (and iphone5 size phones)

### ISSUE THREAD

**Issue by nogainbar** [quaker-social-action/dte-website#200]
footer is on top of cards. 

fixes it if overwriting fp-tableCell to display:block but that surely is not the right way to go.

any help greatly appreciated, i will be able to look into it more tomorrow but a bit at lost with it because have tried debugging for two days with no great success...

**Comment by gabrielperales** [comment]
This is an issue of fullpage.js, I will fix it!
