### ISSUE TITLE
User: personalised packages

### ISSUE THREAD

**Issue by sofiapoh** [quaker-social-action/dte-website#3]
As a user, I want to be able to customise the template package so I can personalise it.

**Comment by DuncanMcLaggan** [comment]
This is where people can personalise and get an idea of basic optional "extras" they can use to make the service more bespoke. 

A basic list of options includes:

o   The basic funeral service cost from issue #1 
o   Flowers 
o   Death / funeral notice
o   Limousine 
o   Order sheets
o   Catering for wake/reception
o   Venue for wake/reception

We have the data to be able to give average regional prices for these.

**Comment by DuncanMcLaggan** [comment]
Pricing data for the optional extras by region emailed through to Richard.

**Comment by DuncanMcLaggan** [comment]
Text for the optional extras page emailed through to Richard
