### ISSUE TITLE
Questions for Wednesday standup

### ISSUE THREAD

**Issue by DuncanMcLaggan** [quaker-social-action/dte-website#35]
Re contact us link - how about make it an "I need help now" button - makes it clear to those who are in immediate need that they can just click there rather than "contact" which is a bit vague. We also don't want joe public  contacting us directly as a result of the planner, unless they are in need. 

Crem v Burial costings - show side by side and then allow for choice? So chose REGION - shows price for crem AND burial - then select CREM or BURIAL??

What and where to add a link if they can't afford their option? Eg they go through 1, 2, or 3 and while they are not in immediate need, they know that these costs are too high - where should they "jump off" and go through to the Info/Advice page?

Client story for option 3 - any point? These are not costs we would push clients to add, as they are completely optional and they could do them themselves. 

Making text changes - process

need to add acknowledgement of where our price calculations come from (SunLife 2016 Cost of Dying report).

**Comment by RichAWarren** [comment]
I help now sounds much better, would this linking to the down to earth page work for the time being?

Region picker, crem/burial picker and basic cost will be on the same page to allow for comparisons and picking and choosing between the two.

Not sure where to add the link, maybe best to wait until you can see the whole flow this afternoon?

Agree on no client story for option 3

**Comment by nogainbar** [comment]
closing issue as was done in last sprint
