### ISSUE TITLE
User: funding options

### ISSUE THREAD

**Issue by sofiapoh** [quaker-social-action/dte-website#7]
As a user, I want to know the funding options if I can't afford the funeral so that I'm not going to get in debt.

**Comment by DuncanMcLaggan** [comment]
See a connection here with issue #9 re contact us. These are the kind of users we would want to come through to our direct service. So we will need a way to ensure that it is clear for users who are immediately facing planning a funeral, are on a low income and can't raise these funds to be able to call us to discuss their options. What we don't want is a situation where general members of the public who have tried out the tool call through for general info... so we need to figure out a clear way to present this.
