### ISSUE TITLE
User: contact us

### ISSUE THREAD

**Issue by sofiapoh** [quaker-social-action/dte-website#9]
As a user, I wan't have a clear idea of who to contact so that I can get more information that I need.

**Comment by DuncanMcLaggan** [comment]
Regarding contacting us - we only want them to contact us for information/support when they are currently faced with planning a funeral (and they also only if they are on a low-income). So we are thinking that the contact details should feature at the front end, directing through to our number where they are looking for **_immediate_** support in planning a funeral and are on a low-income/struggling to meet the costs.
