### ISSUE TITLE
Direct cremation link is incorrect - Link to QSA funeral planning resources

### ISSUE THREAD

**Issue by nogainbar** [quaker-social-action/dte-website#94]

**Comment by nogainbar** [comment]
@DuncanMcLaggan, would you be able to write the right link here?
thank you!

**Comment by DuncanMcLaggan** [comment]
Hi - we can link it to the DtE resrouces at: http://www.quakersocialaction.org.uk/find-out-more-dte

**Comment by nogainbar** [comment]
done
